export const ErrorCodes = {
  // auth
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // validation / request
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED', // ✅ NUEVO

  // users/roles (ejemplos)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PROTECTED: 'ROLE_PROTECTED',

  // tenancy
  TENANT_REQUIRED: 'TENANT_REQUIRED',

  // generic
  INTERNAL: 'INTERNAL',

  // establecimientos
  ESTABLECIMIENTO_NOT_FOUND: 'ESTABLECIMIENTO_NOT_FOUND',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_CONFLICT: 'ASSIGNMENT_CONFLICT',

  // lotes
  LOTE_NOT_FOUND: 'LOTE_NOT_FOUND',
  LOTE_NUMERO_DUPLICADO: 'LOTE_NUMERO_DUPLICADO',
  LOTE_REFERENCED_BY_BANDEJA: 'LOTE_REFERENCED_BY_BANDEJA',
  LOTE_TIPO_IMMUTABLE: 'LOTE_TIPO_IMMUTABLE',

  // siembra
  SIEMBRA_NOT_FOUND: 'SIEMBRA_NOT_FOUND',
  SIEMBRA_HAS_TRASPLANTADAS: 'SIEMBRA_HAS_TRASPLANTADAS',
  SIEMBRA_FIELD_IMMUTABLE: 'SIEMBRA_FIELD_IMMUTABLE',
  BANDEJA_NOT_FOUND: 'BANDEJA_NOT_FOUND',
  LOTE_TIPO_INCORRECTO: 'LOTE_TIPO_INCORRECTO',

  // recetas
  RECETA_NOT_FOUND: 'RECETA_NOT_FOUND',
  RECETA_NOMBRE_DUPLICADO: 'RECETA_NOMBRE_DUPLICADO',
  RECETA_FIELD_IMMUTABLE: 'RECETA_FIELD_IMMUTABLE',

  // quimicos
  QUIMICO_NOT_FOUND: 'QUIMICO_NOT_FOUND',
  QUIMICO_NOMBRE_DUPLICADO: 'QUIMICO_NOMBRE_DUPLICADO',
  QUIMICO_FIELD_IMMUTABLE: 'QUIMICO_FIELD_IMMUTABLE',
  PRINCIPIO_ACTIVO_NOT_FOUND: 'PRINCIPIO_ACTIVO_NOT_FOUND',
  PRINCIPIO_ACTIVO_NOMBRE_DUPLICADO: 'PRINCIPIO_ACTIVO_NOMBRE_DUPLICADO',
  PRINCIPIO_ACTIVO_REFERENCIADO: 'PRINCIPIO_ACTIVO_REFERENCIADO',

  // stock movimientos
  MOVIMIENTO_NOT_FOUND: 'MOVIMIENTO_NOT_FOUND',
  MOVIMIENTO_CANTIDAD_INVALIDA: 'MOVIMIENTO_CANTIDAD_INVALIDA',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
