export const ErrorCodes = {
  // auth
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // validation / request
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED', // ✅ NUEVO

  // users/roles (ejemplos)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PROTECTED: 'ROLE_PROTECTED',

  // tenancy
  TENANT_REQUIRED: 'TENANT_REQUIRED',

  // generic
  INTERNAL: 'INTERNAL',

  // establecimientos
  ESTABLECIMIENTO_NOT_FOUND: 'ESTABLECIMIENTO_NOT_FOUND',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_CONFLICT: 'ASSIGNMENT_CONFLICT',

  // lotes
  LOTE_NOT_FOUND: 'LOTE_NOT_FOUND',
  LOTE_NUMERO_DUPLICADO: 'LOTE_NUMERO_DUPLICADO',
  LOTE_REFERENCED_BY_BANDEJA: 'LOTE_REFERENCED_BY_BANDEJA',
  LOTE_TIPO_IMMUTABLE: 'LOTE_TIPO_IMMUTABLE',
  LOTE_PROVEEDOR_SEMILLA_NO_PERMITIDO: 'LOTE_PROVEEDOR_SEMILLA_NO_PERMITIDO',

  // siembra
  SIEMBRA_NOT_FOUND: 'SIEMBRA_NOT_FOUND',
  SIEMBRA_HAS_TRASPLANTADAS: 'SIEMBRA_HAS_TRASPLANTADAS',
  SIEMBRA_FIELD_IMMUTABLE: 'SIEMBRA_FIELD_IMMUTABLE',
  BANDEJA_NOT_FOUND: 'BANDEJA_NOT_FOUND',
  LOTE_TIPO_INCORRECTO: 'LOTE_TIPO_INCORRECTO',

  // recetas
  RECETA_NOT_FOUND: 'RECETA_NOT_FOUND',
  RECETA_NOMBRE_DUPLICADO: 'RECETA_NOMBRE_DUPLICADO',
  RECETA_FIELD_IMMUTABLE: 'RECETA_FIELD_IMMUTABLE',

  // quimicos
  QUIMICO_NOT_FOUND: 'QUIMICO_NOT_FOUND',
  QUIMICO_NOMBRE_DUPLICADO: 'QUIMICO_NOMBRE_DUPLICADO',
  QUIMICO_FIELD_IMMUTABLE: 'QUIMICO_FIELD_IMMUTABLE',
  PRINCIPIO_ACTIVO_NOT_FOUND: 'PRINCIPIO_ACTIVO_NOT_FOUND',
  PRINCIPIO_ACTIVO_NOMBRE_DUPLICADO: 'PRINCIPIO_ACTIVO_NOMBRE_DUPLICADO',
  PRINCIPIO_ACTIVO_REFERENCIADO: 'PRINCIPIO_ACTIVO_REFERENCIADO',

  // lotes-quimicos
  LOTE_QUIMICO_NOT_FOUND: 'LOTE_QUIMICO_NOT_FOUND',
  LOTE_QUIMICO_NUMERO_DUPLICADO: 'LOTE_QUIMICO_NUMERO_DUPLICADO',
  LOTE_QUIMICO_STOCK_INSUFICIENTE: 'LOTE_QUIMICO_STOCK_INSUFICIENTE',
  LOTE_QUIMICO_REFERENCED: 'LOTE_QUIMICO_REFERENCED',
  LOTE_QUIMICO_FIELD_IMMUTABLE: 'LOTE_QUIMICO_FIELD_IMMUTABLE',

  // tuneles
  TUNEL_NOT_FOUND: 'TUNEL_NOT_FOUND',
  TUNEL_NOMBRE_DUPLICADO: 'TUNEL_NOMBRE_DUPLICADO',
  TUNEL_FIELD_IMMUTABLE: 'TUNEL_FIELD_IMMUTABLE',

  // mesas
  MESA_NOT_FOUND: 'MESA_NOT_FOUND',
  MESA_QR_NOT_FOUND: 'MESA_QR_NOT_FOUND',
  MESA_ESTADO_INVALIDO: 'MESA_ESTADO_INVALIDO',
  MESA_FIELD_IMMUTABLE: 'MESA_FIELD_IMMUTABLE',
  MESA_SOLO_BAJA_DELETE: 'MESA_SOLO_BAJA_DELETE',

  // aplicaciones-quimicas
  APLICACION_NOT_FOUND: 'APLICACION_NOT_FOUND',
  APLICACION_TARGET_INVALIDO: 'APLICACION_TARGET_INVALIDO',
  APLICACION_DETALLES_VACIOS: 'APLICACION_DETALLES_VACIOS',
  APLICACION_TARGETS_VACIOS: 'APLICACION_TARGETS_VACIOS',

  // trasplante
  TRASPLANTE_MESA_ESTADO_INVALIDO: 'TRASPLANTE_MESA_ESTADO_INVALIDO',
  TRASPLANTE_BANDEJA_INVALIDA: 'TRASPLANTE_BANDEJA_INVALIDA',
  TRASPLANTE_ESTABLECIMIENTO_MISMATCH: 'TRASPLANTE_ESTABLECIMIENTO_MISMATCH',

  // cosecha
  COSECHA_NOT_FOUND: 'COSECHA_NOT_FOUND',
  COSECHA_MESA_NO_DISPONIBLE: 'COSECHA_MESA_NO_DISPONIBLE',

  // packing
  PACKING_NOT_FOUND: 'PACKING_NOT_FOUND',
  PACKING_YA_REGISTRADO: 'PACKING_YA_REGISTRADO',
  PACKING_CATEGORIA_DUPLICADA: 'PACKING_CATEGORIA_DUPLICADA',

  // proveedores
  PROVEEDOR_NOT_FOUND: 'PROVEEDOR_NOT_FOUND',
  PROVEEDOR_NOMBRE_DUPLICADO: 'PROVEEDOR_NOMBRE_DUPLICADO',
  PROVEEDOR_FIELD_IMMUTABLE: 'PROVEEDOR_FIELD_IMMUTABLE',
  PROVEEDOR_REFERENCED: 'PROVEEDOR_REFERENCED',
  PROVEEDOR_ESTABLECIMIENTO_MISMATCH: 'PROVEEDOR_ESTABLECIMIENTO_MISMATCH',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
